name: goreleaser

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      -
        name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
      -
        name: Upload artifacts
        env:
          GIT_COMMITTER_NAME: Actions Automation
          GIT_COMMITTER_EMAIL:
          GIT_AUTHOR_NAME: Actions Automation
          GIT_AUTHOR_EMAIL:
        run: |
          git add dist
          git restore --staged dist/config.yaml dist/\*.zip dist/\*.tar.gz dist/\*.txt dist/\*.txt.sig
          git commit -m "Add artifacts for ${GITHUB_REF#refs/tags/}"
          if [[ $GITHUB_REF != *-* ]]; then
            git push origin HEAD:trunk
          fi
